[tool.poetry]
name = "wb-parser"
version = "0.1.0"
description = "Wildberries Parser MVP"
authors = ["User <user@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jinja2 = "^3.1.6"
httpx = {extras = ["http2"], version = "^0.28.1"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
